include:
  - project: "kdanmobile/deployment/cluster-cicd-config"
    ref: master
    file: "/gitlab-ci/node-brakeman-sast-upload.yaml"

stages:
  - test
  - sast_upload
  - rspec
  - publish

rspec:
  stage: rspec
  image: ruby:3.4.5
  tags:
    - arm64
  script:
    - bundle config set --local path 'vendor/bundle'
    - RELEASE_VERSION=$(cat VERSION.md)
    - gem build rpdoc.gemspec
    - gem install rpdoc-$RELEASE_VERSION.gem --local
    - bundle install
    - RPDOC_ENABLE=false bundle exec rspec spec
  only:
    - master

to_gem:
  stage: publish
  image: ruby:3.4.5
  tags:
    - arm64
  script:
    - mkdir -p ~/.gem
    - touch ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - 'printf -- "---\n:rubygems_api_key: $GEM_HOST_API_KEY\n" > ~/.gem/credentials'
    - RELEASE_VERSION=$(cat VERSION.md)
    - GEM_NAME=rpdoc-$RELEASE_VERSION.gem
    - gem build rpdoc.gemspec
    - gem push $GEM_NAME
  only:
    - /release-\d+\.\d+\.\d+(\.\d+)?/
