AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 10
